CREATE TABLE posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  body VARCHAR(280) NOT NULL,
  image_path VARCHAR(255),
  created_at VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at VARCHAR(32) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_posts_created_at ON posts (created_at, id);
CREATE INDEX idx_posts_user_id ON posts (user_id);
